-- 001_init.sql
-- Authors: Jovanna, Jovanni, Brandon
-- Description: Schema creation for University Registration System

-- Create students table to hold student info
CREATE TABLE "Students" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "firstName" varchar,
  "lastName" varchar,
  "email" varchar UNIQUE
);

-- Create Course tables
CREATE TABLE "Courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "courseNumber" varchar,
  "courseName" varchar,
  "departmentID" int,
  "levelID" int
);

-- Create Section tables
CREATE TABLE "Sections" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sectionNumber" varchar,
  "semester" varchar,
  "year" int,
  "courseID" int,
  "instructorID" int,
  "statusID" int
);

-- Create Department tables
CREATE TABLE "Departments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "departmentName" varchar,
  "headOfDepartmentID" int
);

-- Create Instructor tables
CREATE TABLE "Instructors" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "firstName" varchar,
  "lastName" varchar,
  "startDate" date,
  "departmentID" int
);

-- Create Staff tables
CREATE TABLE "Staff" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "firstName" varchar,
  "lastName" varchar,
  "startDate" date,
  "role" varchar
);

-- Create Enrollment tables
CREATE TABLE "Enrollments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "studentID" int,
  "sectionID" int,
  "enrollmentDate" date
);

-- Create Payrolltables
CREATE TABLE "Payroll" (
  "id" int PRIMARY KEY,
  "salary" decimal,
  "payPeriod" varchar
);

CREATE TABLE "CourseLevels" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "levelName" varchar
);

CREATE TABLE "SectionStatus" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "statusName" varchar
);

-- constrain course numbers to unique numbers within department
CREATE UNIQUE INDEX ON "Courses" ("courseNumber", "departmentID");

-- enrollment holds unique studentID for each section ID
CREATE UNIQUE INDEX ON "Enrollments" ("studentID", "sectionID");

-- creates comments for email
COMMENT ON COLUMN "Students"."email" IS 'Email must be unique';

-- creates comments for headOfDepartmentID required
COMMENT ON COLUMN "Departments"."headOfDepartmentID" IS 'Must have one head of department';

-- create comment for section status
COMMENT ON COLUMN "SectionStatus"."statusName" IS 'Must be one of: {Open, In Progress, Closed, Waitlisted, Canceled}';


-- create link: courses to their owning deparment
ALTER TABLE "Courses" ADD FOREIGN KEY ("departmentID") REFERENCES "Departments" ("id") DEFERRABLE INITIALLY IMMEDIATE;

-- create link: instructor to their owning department
ALTER TABLE "Instructors" ADD FOREIGN KEY ("departmentID") REFERENCES "Departments" ("id") DEFERRABLE INITIALLY IMMEDIATE;

-- create link: section to their owning course
ALTER TABLE "Sections" ADD FOREIGN KEY ("courseID") REFERENCES "Courses" ("id") DEFERRABLE INITIALLY IMMEDIATE;

-- create link: section to their owning instructor
ALTER TABLE "Sections" ADD FOREIGN KEY ("instructorID") REFERENCES "Instructors" ("id") DEFERRABLE INITIALLY IMMEDIATE;

-- create link: course to their owning level
ALTER TABLE "Courses" ADD FOREIGN KEY ("levelID") REFERENCES "CourseLevels" ("id") DEFERRABLE INITIALLY IMMEDIATE;

-- create link: section to their owning section status
ALTER TABLE "Sections" ADD FOREIGN KEY ("statusID") REFERENCES "SectionStatus" ("id") DEFERRABLE INITIALLY IMMEDIATE;

-- create link: enrollment to their owning student
ALTER TABLE "Enrollments" ADD FOREIGN KEY ("studentID") REFERENCES "Students" ("id") DEFERRABLE INITIALLY IMMEDIATE;

-- create link: enrollment to their owning section
ALTER TABLE "Enrollments" ADD FOREIGN KEY ("sectionID") REFERENCES "Sections" ("id") DEFERRABLE INITIALLY IMMEDIATE;

-- create link: payrol to their owning staff
ALTER TABLE "Payroll" ADD FOREIGN KEY ("id") REFERENCES "Staff" ("id") DEFERRABLE INITIALLY IMMEDIATE;

-- create link: department to their owning head of department referencing instructors
ALTER TABLE "Departments" ADD FOREIGN KEY ("headOfDepartmentID") REFERENCES "Instructors" ("id") DEFERRABLE INITIALLY IMMEDIATE;
